import { Check, CheckCircle2, FileText, Lightbulb, Sparkles, X } from "lucide-react";
import { useState } from "react";
import { Link } from "react-router-dom";
import CandidatePageShell from "../components/CandidatePageShell";
import { useCandidate } from "../components/CandidateProvider";

export default function CandidateSuggestionsPage() {
  const { analysis, loading } = useCandidate();
  const [decisions, setDecisions] = useState({});
  if (loading) return <CandidatePageShell><div className="center-panel"><span className="spinner" /> Loading suggestions…</div></CandidatePageShell>;
  if (!analysis) return <CandidatePageShell><div className="no-analysis-inline"><FileText /><h1>No suggestions yet.</h1><p>Analyze a resume first.</p><Link className="button button-primary" to="/candidate/dashboard">Go to Overview</Link></div></CandidatePageShell>;
  return <CandidatePageShell><div className="dashboard suggestions-page"><div className="page-title"><div><h1>Your improvement plan</h1><p>Ordered by expected value. You remain in control of every wording change.</p></div></div><div className="suggestion-layout"><main><section className="action-plan"><header><h2>Highest-impact actions</h2><span>{analysis.losses.length} items</span></header>{analysis.losses.map((loss, index) => <article key={loss.title}><b>{index + 1}</b><div><span>{loss.category} · up to {loss.points} points</span><h3>{loss.title}</h3><p>{loss.action}</p>{loss.evidence ? <blockquote>“{loss.evidence.text}”</blockquote> : null}</div></article>)}</section><section className="rewrite-list"><header><Sparkles /><div><h2>Truth Lock rewrites</h2><p>Wording can improve; facts cannot change.</p></div></header>{analysis.rewrites.length ? analysis.rewrites.map((rewrite) => <article key={rewrite.line}><div><span>Original · line {rewrite.line}</span><p>{rewrite.original}</p></div><div className="suggested"><span>Suggested</span><p>{rewrite.suggested}</p></div><div><span>Why</span><p>{rewrite.reason}</p>{rewrite.missingInformation ? <small><Lightbulb /> {rewrite.missingInformation}</small> : null}</div><footer>{decisions[rewrite.line] ? <strong className={decisions[rewrite.line]}><CheckCircle2 /> {decisions[rewrite.line]}</strong> : <><button className="button button-primary" onClick={() => setDecisions((current) => ({ ...current, [rewrite.line]: "approved" }))}><Check /> Approve</button><button className="button button-secondary" onClick={() => setDecisions((current) => ({ ...current, [rewrite.line]: "rejected" }))}><X /> Reject</button></>}</footer></article>) : <div className="inline-success"><CheckCircle2 /> No unsafe or weak bullet openings need automatic rewriting.</div>}</section></main><aside className="strength-list"><h2>What already works</h2>{analysis.strengths.map((strength) => <article key={strength.title}><CheckCircle2 /><div><strong>{strength.title}</strong>{strength.evidence ? <p>“{strength.evidence.text}”</p> : null}</div></article>)}</aside></div></div></CandidatePageShell>;
}
