import { ArrowRight, FileText, Info, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { Link } from "react-router-dom";
import CandidatePageShell from "../components/CandidatePageShell";
import { useCandidate } from "../components/CandidateProvider";

export default function CandidateAnalysisPage() {
  const { analysis, loading } = useCandidate();
  const [selectedLoss, setSelectedLoss] = useState(0);
  if (loading) return <CandidatePageShell><div className="center-panel"><span className="spinner" /> Loading analysis…</div></CandidatePageShell>;
  if (!analysis) return <CandidatePageShell><div className="no-analysis-inline"><FileText /><h1>No resume has been analyzed yet.</h1><p>Return to Overview and start your first analysis.</p><Link className="button button-primary" to="/candidate/dashboard">Go to Overview</Link></div></CandidatePageShell>;
  const selectedLine = analysis.losses[selectedLoss]?.evidence?.line;
  return <CandidatePageShell><div className="dashboard"><div className="page-title"><div><h1>Detailed resume analysis</h1><p>{analysis.role.targetRole} · Evidence and deductions</p></div><span className="model-label"><ShieldCheck /> {analysis.metadata.rubricVersion}</span></div><section className="score-breakdown analysis-breakdown"><header><h2>Score breakdown</h2><Info /></header><div>{analysis.categories.map((category) => <div className="metric" key={category.name}><span>{category.name}</span><strong>{category.score}<small>/100</small></strong><i><b style={{ width: `${category.score}%` }} /></i></div>)}</div></section><div className="evidence-grid analysis-evidence-grid"><section className="loss-panel"><header><h2>Why you lost marks</h2><span>{analysis.losses.reduce((sum, item) => sum + item.points, 0)} pts explained</span></header>{analysis.losses.map((loss, index) => <button className={`loss-row ${selectedLoss === index ? "selected" : ""}`} key={`${loss.category}-${loss.title}`} onClick={() => setSelectedLoss(index)}><span className={`status-dot ${loss.points >= 5 ? "risk" : "warning"}`} /><span><strong>{loss.title}</strong><small>{loss.detail}</small>{loss.evidence ? <em>Line {loss.evidence.line}: “{loss.evidence.text}”</em> : <em>Missing evidence</em>}</span><b>-{loss.points}</b></button>)}</section><section className="resume-panel"><header><div><FileText /><span><strong>Parsed resume</strong><small>{analysis.resume.wordCount} words · select a deduction to locate it</small></span></div></header><div className="resume-paper analysis-paper">{analysis.resume.lines.map((line) => { const strong = analysis.strengths.some((item) => item.evidence?.line === line.line); const weak = analysis.losses.some((item) => item.evidence?.line === line.line); return <p className={selectedLine === line.line ? "line-selected" : strong ? "line-strong" : weak ? "line-weak" : ""} key={line.line}><span>{line.line}</span>{line.text}</p>; })}</div><footer><span><i className="legend-good" /> Strong evidence</span><span><i className="legend-weak" /> Needs work</span></footer></section></div><div className="analysis-next"><span>Ready to act on the findings?</span><Link className="button button-primary" to="/candidate/suggestions">Open all suggestions <ArrowRight /></Link></div></div></CandidatePageShell>;
}
