import { AlertCircle, ArrowUpDown, CheckCircle2, ChevronDown, EyeOff, FilePlus2, GitCompareArrows, Info, MessageSquareText, Search, SlidersHorizontal, Sparkles, Star, UserRound, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import AppShell from "../components/AppShell";
import { api } from "../lib/api";

const weightDefaults = { skills: 35, experience: 25, evidence: 20, impact: 15, education: 5 };

function CandidateDrawer({ candidate, blind, onClose }) {
  const [tab, setTab] = useState("Overview");
  const [questions, setQuestions] = useState([]);
  const [busy, setBusy] = useState(false);
  const generate = async () => { setBusy(true); try { const data = await api("/recruiter/interview-questions", { method: "POST", body: JSON.stringify({ candidateId: candidate.id }) }); setQuestions(data.questions); setTab("Interview"); } finally { setBusy(false); } };
  return <aside className="candidate-drawer"><header><div className="large-avatar">{blind ? String(candidate.rank).padStart(2, "0") : candidate.initials}</div><div><h2>{blind ? `Candidate ${String(candidate.rank).padStart(2, "0")}` : candidate.name}</h2><p>{candidate.years} years experience · {blind ? "Identity hidden" : candidate.location}</p></div><button className="icon-button" onClick={onClose} aria-label="Close candidate"><X /></button></header><div className="drawer-tabs">{["Overview", "Evidence", "Notes", "Interview"].map((name) => <button className={tab === name ? "active" : ""} onClick={() => setTab(name)} key={name}>{name}</button>)}</div>
    {tab === "Overview" ? <><div className="candidate-kpis"><div><span>Fit score</span><strong>{candidate.fit}<small>/100</small></strong></div><div><span>Confidence</span><strong className="success">{candidate.confidence >= 70 ? "High" : candidate.confidence >= 50 ? "Medium" : "Low"}</strong></div><div><span>Mandatory</span><strong>{candidate.mandatory}<small>/5</small></strong></div><div><span>Rank</span><strong>#{candidate.rank}</strong></div></div><section className="drawer-section"><h3>Strengths</h3>{candidate.strengths.map((item) => <p className="positive" key={item}><CheckCircle2 /> {item}</p>)}</section><section className="drawer-section"><h3>Gaps to verify</h3>{candidate.gaps.map((item) => <p className="caution" key={item}><AlertCircle /> {item}</p>)}</section><section className="drawer-section"><h3>Top evidence excerpts</h3>{candidate.excerpts.map((item, index) => <blockquote key={item}><MessageSquareText /><div><strong>{index === 0 ? "Relevant ownership" : "Measured impact"}</strong><p>“{item}”</p><small>Resume · evidence line {index + 12}</small></div></blockquote>)}</section></> : null}
    {tab === "Evidence" ? <section className="drawer-section"><h3>Evidence feature map</h3>{Object.entries(candidate.features || {}).map(([key, value]) => <div className="evidence-feature" key={key}><span>{key}</span><i><b style={{ width: `${value}%` }} /></i><strong>{Math.round(value)}</strong></div>)}</section> : null}
    {tab === "Notes" ? <section className="drawer-section"><h3>Private recruiter note</h3><textarea rows="8" placeholder="Add a verification item or interview observation…" /><button className="button button-primary">Save note</button></section> : null}
    {tab === "Interview" ? <section className="drawer-section"><h3>Evidence-based interview questions</h3>{questions.length ? <ol className="question-list">{questions.map((question) => <li key={question}>{question}</li>)}</ol> : <div className="empty-state"><Sparkles /><p>Generate questions from the candidate's evidence and gaps.</p></div>}</section> : null}
    <footer><div><span>Uncertainty</span><strong>{100 - candidate.confidence}%</strong><small>{candidate.confidence >= 70 ? "Low" : "Review needed"}</small></div><button className="button button-primary" onClick={generate} disabled={busy}><Sparkles /> {busy ? "Generating…" : "Generate interview questions"}</button></footer>
  </aside>;
}

export default function RecruiterDashboard() {
  const [candidates, setCandidates] = useState([]);
  const [weights, setWeights] = useState(weightDefaults);
  const [selected, setSelected] = useState(new Set(["c2", "c3"]));
  const [activeCandidate, setActiveCandidate] = useState(null);
  const [blind, setBlind] = useState(false);
  const [search, setSearch] = useState("");
  const [skills, setSkills] = useState(new Set(["React"]));
  const [loading, setLoading] = useState(true);
  useEffect(() => { api("/recruiter/rankings").then(({ candidates: rows }) => { setCandidates(rows); setActiveCandidate(rows[1] || rows[0]); }).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (loading) return undefined; const timer = setTimeout(() => { api("/recruiter/rerank", { method: "POST", body: JSON.stringify({ weights }) }).then(({ candidates: rows }) => { setCandidates(rows); setActiveCandidate((current) => rows.find((item) => item.id === current?.id) || rows[0]); }); }, 250); return () => clearTimeout(timer); }, [weights, loading]);
  const visible = useMemo(() => candidates.filter((candidate) => (!search || `${candidate.name} ${candidate.location}`.toLowerCase().includes(search.toLowerCase())) && [...skills].every((skill) => candidate.skills.includes(skill))), [candidates, search, skills]);
  const toggleSelected = (id) => setSelected((current) => { const next = new Set(current); next.has(id) ? next.delete(id) : next.add(id); return next; });
  const toggleSkill = (skill) => setSkills((current) => { const next = new Set(current); next.has(skill) ? next.delete(skill) : next.add(skill); return next; });
  return <AppShell role="employer" action={<><label className="header-search"><Search /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search candidates" /></label><button className="button button-primary"><FilePlus2 /> Add candidates</button></>}>
    <div className="recruiter-dashboard"><section className="job-heading"><div><h1>Senior Frontend Engineer <Star /></h1><p>Bengaluru · 18 applicants · Updated today</p></div><button className="button button-secondary"><SlidersHorizontal /> Edit rubric</button></section>
      <section className="weights"><header><div><h2>Rubric weighting</h2><p>Adjust the role-specific ranking signals.</p></div><span>Total {Object.values(weights).reduce((sum, value) => sum + value, 0)}%</span></header><div>{Object.entries(weights).map(([key, value]) => <label key={key}><span>{key}</span><strong>{value}%</strong><input type="range" min="0" max="60" value={value} onChange={(event) => setWeights((current) => ({ ...current, [key]: Number(event.target.value) }))} /></label>)}</div></section>
      <div className="recruiter-body"><aside className="filter-rail"><header><h2>Filters</h2><button>Clear all</button></header><div className="filter-section"><h3>Confidence <ChevronDown /></h3><label><input type="checkbox" defaultChecked /> High <span>3</span></label><label><input type="checkbox" defaultChecked /> Medium <span>3</span></label><label><input type="checkbox" /> Low <span>2</span></label></div><div className="filter-section"><h3>Skills <ChevronDown /></h3>{["React", "TypeScript", "Next.js", "Testing"].map((skill) => <label key={skill}><input type="checkbox" checked={skills.has(skill)} onChange={() => toggleSkill(skill)} /> {skill}<span>{candidates.filter((item) => item.skills.includes(skill)).length}</span></label>)}</div><div className="filter-section"><h3>Experience <ChevronDown /></h3><div className="experience-range"><span>2 years</span><span>10+ years</span></div><input type="range" min="0" max="10" defaultValue="2" /></div><div className="blind-control"><EyeOff /><div><strong>Blind screening</strong><span>Hide identity fields</span></div><button className={`toggle ${blind ? "on" : ""}`} onClick={() => setBlind((value) => !value)} aria-label="Toggle blind screening"><i /></button></div></aside>
        <section className="ranking-surface"><div className="stage-tabs">{[["All", 18], ["Applied", 8], ["Screened", 6], ["Shortlisted", 4], ["Interview", 2], ["Decision", 0]].map(([label, count], index) => <button className={index === 0 ? "active" : ""} key={label}>{label} <span>{count}</span></button>)}</div><div className="table-toolbar"><div><span>{selected.size} selected</span><button className="button button-secondary"><GitCompareArrows /> Compare</button><button className="button button-ghost">Move to stage <ChevronDown /></button></div><button className="button button-ghost"><ArrowUpDown /> Sort: Fit score</button></div>
          <div className="candidate-table" role="table" aria-label="Ranked candidates"><div className="table-row table-head" role="row"><span /><span>Candidate</span><span>Fit</span><span>Confidence</span><span>Mandatory</span><span>Evidence</span><span>Stage</span></div>{loading ? <div className="table-loading"><span className="spinner" /> Ranking candidates…</div> : visible.map((candidate) => <button className={`table-row ${activeCandidate?.id === candidate.id ? "active" : ""}`} role="row" key={candidate.id} onClick={() => setActiveCandidate(candidate)}><span onClick={(event) => event.stopPropagation()}><input type="checkbox" checked={selected.has(candidate.id)} onChange={() => toggleSelected(candidate.id)} aria-label={`Select ${candidate.name}`} /></span><span className="candidate-cell"><i>{blind ? String(candidate.rank).padStart(2, "0") : candidate.initials}</i><span><strong>{blind ? `Candidate ${String(candidate.rank).padStart(2, "0")}` : candidate.name}</strong><small>{candidate.years} yrs · {blind ? "Identity hidden" : candidate.location}</small></span></span><span className="fit-cell"><strong>{candidate.fit}</strong><i><b style={{ width: `${candidate.fit}%` }} /></i></span><span className="confidence-cell"><i className={candidate.confidence >= 70 ? "high" : candidate.confidence >= 50 ? "medium" : "low"} /><span>{candidate.confidence >= 70 ? "High" : candidate.confidence >= 50 ? "Medium" : "Low"}<small>{candidate.confidence}%</small></span></span><span><CheckCircle2 className={candidate.mandatory === 5 ? "green" : "amber"} /> {candidate.mandatory}/5</span><span><MessageSquareText /> {candidate.evidence}</span><span className="stage-select">{candidate.stage}<ChevronDown /></span></button>)}</div>
          <footer className="decision-note"><Info /> HireLens provides evidence-based decision support. Final hiring decisions remain human-controlled.</footer>
        </section>{activeCandidate ? <CandidateDrawer candidate={activeCandidate} blind={blind} onClose={() => setActiveCandidate(null)} /> : <aside className="candidate-drawer drawer-empty"><UserRound /><h2>Select a candidate</h2><p>Open any row to inspect evidence, gaps and interview questions.</p></aside>}
      </div>
    </div>
  </AppShell>;
}
